GET http://localhost:3001/api/blogs

# POST  http://localhost:3001/api/blogs
# Content-Type: application/json

# {
#     "title" : "Part 4 BLog",
#     "author" : "SC",
#     "url" : "http://asdsa.com",
#     "likes" : 34
# }