# DELETE http://localhost:3001/api/persons/2

POST  http://localhost:3001/api/persons
Content-Type: application/json

{
    "name" : "Arto Hellas",
    "number" : "232132"
}

GET http://localhost:3002/api/persons